# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c743f9366f337e69f37f74a1071f8f805a062c5a4c82837fea36f779dd0d796dadc881e027cca349a63dec3b56e1571990630938b477767ed399f782df7baa47

test:
  secret_key_base: d44671fe28b5509f0a9eb5b3f6e1747bea90c0bfcbcd7ece782abe07be76700f67096f5be56bca31a1aad29493120f859904600fbc3e2deebc246d628e8acc43

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
